name: vdo_ninja
description: Simple capture app for VDO.NInja
version: 1.0.2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_webrtc: ^0.6.8
  shared_preferences: ^2.0.8
  http: ^0.13.3
  path_provider: ^2.0.5
  wakelock: ^0.5.6
  js: ^0.6.3
  share: ^2.0.4
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
