name: vdo_ninja
description: Simple capture app for VDO.NInja
version: 5.0.7+7
versionCode: 7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.9.19
  shared_preferences: ^2.0.8
  http: ^0.13.3
  path_provider: ^2.0.2
  wakelock: ^0.6.1+1
  js: ^0.6.3
  share: ^2.0.4
  url_launcher: ^6.0.12
  flutter_background:
    git:
      url: flutter_background
      ref: master    

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
  uses-material-design: true
