name: vdo_ninja
description: Simple capture app for VDO.Ninja
version: 5.0.38+38
versionCode: 38
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter_webrtc: ^0.13.0
  shared_preferences: ^2.5.3
  http: ^1.3.0
  path_provider: ^2.0.2
  wakelock_plus: ^1.1.4
  js: ^0.6.7
  share_plus: ^7.2.2
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.14
  permission_handler: ^11.4.0
  encrypt: ^5.0.1
  tuple: ^2.0.2
  device_info_plus: ^11.0.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  win32: ^5.8.0
flutter:
  uses-material-design: true