name: VDO.Ninja
description: Simple capture app for VDO.NInja
version: 1.0.2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_webrtc: ^0.6.5
  shared_preferences: ^2.0.6
  http: ^0.12.1
  path_provider: ^2.0.1
  wakelock: ^0.5.2
  html: ^0.15.0
  js: ^0.6.3
  share: ^2.0.4
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
